### PR TITLE
Login system

### PR DESCRIPTION
**Pull request by 48panda48**
So mongoose makes your collection query lowercase quietly.
MongoDB doesn't mention this and this was our problem.

(I had this exact problem like 10 hours ago and i completely forgot :( )

### CODE REVIEW

**Comment by lyallstewart** [comment]
At least it works now! :)

**Comment by lyallstewart** [comment]
Nice job btw

**Review by lyallstewart — COMMENTED** [review]
👍

**Review by lyallstewart — APPROVED** [review]

**Comment by 48panda48** [comment]
I literally changed 6 lines in that last commit *sigh*

**Pull request merged**
